export default {
  OAUTH_CLIENT_ID: process.env.OAUTH_CLIENT_ID,
  OAUTH_CLIENT_SECRET: process.env.OAUTH_CLIENT_SECRET,
  OAUTH_REDIRECT_URL: process.env.OAUTH_REDIRECT_URL,
  OAUTH_API_KEY: process.env.OAUTH_API_KEY,
};
